name: 🐞 Bug Report
description: File a bug report to help us improve the engine.
title: "[BUG] - "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "Thank you for helping make the ALIZARIN Engine better! Please provide as much detail as possible so we can fix this."
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "How can we reproduce the issue? (e.g., 1. Run `train.py` with X config... 2. See error...)"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: logs
    attributes:
      label: Logs, Errors, & Screenshots
      description: "Please paste any relevant console output, error logs, or screenshots here. Use code blocks for logs."
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
